title: Blogs by Bing
author: Bing Jang
email: bjang1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This blog will explore the things I have learnt in ICS20. So far I have learnt drawing with JS, and a reasonable amount of HTML

# social links
twitter_username: n/a
github_username:  bjang1

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
